<?xml version="1.0" encoding="utf-8"?><Database Name="db_ketoan_admin" Class="ketoanadminDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ADMIN12\SQLEXPRESS;Initial Catalog=db_ketoan_admin;Persist Security Info=True;User ID=quanly" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="db_ketoan_adminConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Appcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Appnumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="Customer_CustomerSetup" Member="CustomerSetups" ThisKey="ID" OtherKey="CustomerID" Type="CustomerSetup" />
    </Type>
  </Table>
  <Table Name="dbo.CustomerSetup" Member="CustomerSetups">
    <Type Name="CustomerSetup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fullname" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HddSeriID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="Customer_CustomerSetup" Member="Customer" ThisKey="CustomerID" OtherKey="ID" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="Saft" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="RoleID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>